[package]
name = "learngl-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
glfw = "0.60.0"
nalgebra-glm = "0.20.0"
tobj = { version ="4.0.3", features = ["reordering", "merging"] }
