[package]
name = "learngl-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
gltf = "1.4.1"
nalgebra-glm = "0.20.0"
sdl2 = { version = "0.38.0"}
obj-rs = {version = "0.7.4", features = ["glium"]}
tobj = "4.0.3"
