[package]
name = "learngl-rs"
version = "0.1.0"
edition = "2024"

[[example]]
name = "simple"

[dependencies]
asset-importer = "0.4.0"
gl = "0.14.0"
image = "0.25.9"
itertools = "0.14.0"
nalgebra-glm = "0.20.0"
sdl2 = { version = "0.38.0"}
